### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by MohamedArteta** [danielTobon43/DBScan-PCL-Optimized#2]
Hello Daniel,
when I test the code, I always get illegal instruction (core dumped). Can you please help me solve this problem?
Thanks in advance.

**Comment by ghost** [comment]
Hello,

Sorry for the reply late. 
Can you post a picture of what are you doing?

**Comment by MohamedArteta** [comment]
Hello Daniel,
thanks for replying. I tried to run the code on my private laptop and it worked and generated the clusters as it should be, but when I try to run the code on a PC at work, it gives me an Error ('illegal instructions core dumped').
![Screenshot from 2019-09-11 12-23-24](https://user-images.githubusercontent.com/50120454/64689909-89462c00-d48f-11e9-9770-40a212ba236e.png)

**Comment by ghost** [comment]
It seems a problem with reading the input arguments from the terminal. Are you sure that you have a folder named "dbscan7examples"?

**Comment by ghost** [comment]
I think the problem is in the arg for input path and output path.
You typed on terminal ` /home/ NO USER NAME/ dbscan7examples/...           ...     /home/ NO USER NAME/dbscan`

Should be: `/home/user-name/dbscan7example...`
In your case, your user name is: **`@gamea`**, so the command line would be:

`./dbscan /home/gamea/dbscan7examples/lsm_cat.pcd 124 40 5 5 /home/gamea/dbscan`
